version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '8081:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  demo-frontend:
    build:
      context: ../bug-a-ctrl-demo-frontend
      dockerfile: Dockerfile
    container_name: demo-frontend
    restart: 'unless-stopped'
    networks:
      - backend
  frontend:
    build:
      context: ../bug-a-ctrl-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
      - mariadb-network

networks:
  backend:
    driver: bridge
  mariadb-network:
    driver: bridge

volumes:
  data:
    driver: local
